//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhanMenHocTiengTrungAPI.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class BaiHoc
    {
        [DisplayName("ID")]
        public int id { get; set; }
        [DisplayName("Chủ đề")]
        public string chude { get; set; }
        [DisplayName("ID Video Youtube")]
        public string idYoutube { get; set; }
        public Nullable<int> diem { get; set; }
    }
}
