//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhanMenHocTiengTrungAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PhanMemHocTiengTrungEntities : DbContext
    {
        public PhanMemHocTiengTrungEntities()
            : base("name=PhanMemHocTiengTrungEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BaiDaHoc> BaiDaHocs { get; set; }
        public virtual DbSet<BaiHoc> BaiHocs { get; set; }
        public virtual DbSet<BaiKiemTra> BaiKiemTras { get; set; }
        public virtual DbSet<ChiTietBaiHoc> ChiTietBaiHocs { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoans { get; set; }
    
        public virtual ObjectResult<Pro_BaiDaHoc_Result> Pro_BaiDaHoc(Nullable<int> idTaiKhoan)
        {
            var idTaiKhoanParameter = idTaiKhoan.HasValue ?
                new ObjectParameter("idTaiKhoan", idTaiKhoan) :
                new ObjectParameter("idTaiKhoan", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pro_BaiDaHoc_Result>("Pro_BaiDaHoc", idTaiKhoanParameter);
        }
    
        public virtual ObjectResult<Pro_BaiKiemTra_Result> Pro_BaiKiemTra(Nullable<int> idTaiKhoan)
        {
            var idTaiKhoanParameter = idTaiKhoan.HasValue ?
                new ObjectParameter("idTaiKhoan", idTaiKhoan) :
                new ObjectParameter("idTaiKhoan", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pro_BaiKiemTra_Result>("Pro_BaiKiemTra", idTaiKhoanParameter);
        }
    
        public virtual ObjectResult<Pro_ChiTietBaiHoc_Result> Pro_ChiTietBaiHoc(Nullable<int> idBaiHoc)
        {
            var idBaiHocParameter = idBaiHoc.HasValue ?
                new ObjectParameter("idBaiHoc", idBaiHoc) :
                new ObjectParameter("idBaiHoc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pro_ChiTietBaiHoc_Result>("Pro_ChiTietBaiHoc", idBaiHocParameter);
        }
    }
}
