//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhanMenHocTiengTrungAPI.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class TaiKhoan
    {
        
        public int id { get; set; }
        [DisplayName("Email")]
        public string email { get; set; }
        [DisplayName("Họ tên")]
        public string hoten { get; set; }
        [DisplayName("Ngày sinh")]
        public string ngaysinh { get; set; }
        [DisplayName("SĐT")]
        public string sdt { get; set; }
        [DisplayName("Hình ảnh")]
        public string hinhanh { get; set; }
        [DisplayName("Level")]
        public Nullable<int> level { get; set; }
        [DisplayName("Admin")]
        public Nullable<bool> isAdmin { get; set; }
    }
}
